# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Processing
      uses: ifP1/setup-processing@v1.0.2
      with:
       # Version of Processing, e.g. 3.5.4
       version: 3.5.4 # default is 3.5.4
       # e.g. 'windows64.zip', 'windows32.zip', 'linux64.tgz'
       platform-filetype: linux64.tgz # optional, default is linux64.tgz
